### ISSUE TITLE
Navigation page - null Application.Current

### ISSUE THREAD

**Issue by IeuanWalker** [dhindrik/TinyInsights.Maui#21]
The current sample app works completely fine, but when testing my production app I noticed the AutoPageTracking not working.

After debugging for some reason the `Application.Current` is null so it fails to setup the page tracking - 
![image](https://github.com/user-attachments/assets/36bcbf49-6a6e-4a50-931a-76afd4ae4c01)

Ive created a repo project here - 
https://github.com/IeuanWalker/TinyInsights.Maui/tree/NullRepo

The only difference between that and the sample is the sample is `Shell` and the repo is `NavigationPage`.

**Comment by dhindrik** [comment]
I know what the problem is. MainPage is injected into the App class. That means that the provider is created before the App class is created. 

If you do like this it should work:

```csharp
        public App(IServiceProvider serviceProvider)
        {
            InitializeComponent();

            MainPage = new NavigationPage(serviceProvider.GetRequiredService<MainPage>());
        }
```

**Comment by IeuanWalker** [comment]
mmm thats fixed it for the repo, but not my production app :/
Will keep debugging

**Comment by IeuanWalker** [comment]
@dhindrik Interesting, so there was 2 reasons why it was null, 
- The one you mentioned above, about DI and the app.cs
- At the bottom of the MainProgram.cs was trying to set the user language before any stats went to application insights - 
```csharp
MauiApp result = builder.Build();

insights = result.Services.GetService<IInsights>();
insights?.UpsertGlobalProperty("Language", AppSettings.IsWelsh ? "cy-GB" : "en-GB");

return result;
```
Not a big deal I can move that too the app.cs
