### ISSUE TITLE
Set the Cloud.RoleName property

### ISSUE THREAD

**Issue by JohanO** [dhindrik/TinyInsights.Maui#27]
Hi, Daniel!

I am currently using TinyInsights in my apps. It works well, but In one case I need to set the 'Cloud.RoleName' property of the TelemetryClient. It needs to be a specific value to fit the rest of the system I am working with. Problem is I can't access it. 
Would an additional 'OverrideCloudRoleName' method, in the same style as 'OverrideAnonymousUserId' be a viable solution?

I would be happy to do the change and submit a PR if you think this is a good solution, or do the implementation if you have a better idéa.

Cheers,
Johan

**Comment by dhindrik** [comment]
Have you tried the UpsertGlobalProperty method?

**Comment by JohanO** [comment]
Yes, I have. It does add a 'cloud_RoleName' property, but under 'customDimensions'. This means we have to query with 'where customDimensions['cloud_RoleName'] = "something"' instead of 'where cloud_RoleName = "something"'. It's a workaround, but I would rather have a real solution.

**Comment by dhindrik** [comment]
I have created a PR that solves this problem, what do you think about this solution? I don't want to add to much "override property methods" in the interface.

**Comment by dhindrik** [comment]
@JohanO Thank you for contributing to the library!
