### ISSUE TITLE
Using both IInsights and ILogger

### ISSUE THREAD

**Issue by JohanO** [dhindrik/TinyInsights.Maui#31]
Today we have one method to register TinyInsight as the IInsights interface and another to register as ILogger, but how about a method to register both interfaces? Then we could use ILogger for common logging (and my project have a lot of code doing that), and use IInsights for setting userID, adding custom properties and all other ApplicationInsight specific things.

I have already added a method to do that in my app, but it would be nice to have it supported by the package.

My code:
```csharp
        var provider = new ApplicationInsightsProvider(applicationInsightsConnectionString);
        configureProvider.Invoke(provider);
        provider.Initialize();

        var insights = new Insights();
        insights.AddProvider(provider);

        services
            .AddSingleton<IInsights>(insights)
            .AddSingleton<ILogger>(provider)
            .AddTransient<InsightsMessageHandler>();
```

**Comment by dhindrik** [comment]
I take a look at it.

**Comment by dhindrik** [comment]
I added a GetProviders method so you can manually register it. I tried other approaches, but I found some problems with it. 

You can now do like this


```csharp
builder.Services.AddSingleton<ILogger>((serviceProvider) =>
        {
            var insights = serviceProvider.GetRequiredService<IInsights>();
            var providers = insights.GetProviders();

            if (providers.Any())
            {
                return (ILogger)providers.First();
            }

            throw new InvalidOperationException("No insights provider found");
        });
```

I also update the sample project with it.
