### ISSUE TITLE
Session Always Shows as 1 in Application Insights

### ISSUE THREAD

**Issue by sang-hyeon** [dhindrik/TinyInsights.Maui#34]
Every time I start multiple sessions, they all appear as the same session.

**Comment by dhindrik** [comment]
I have added a method (https://github.com/dhindrik/TinyInsights.Maui/commit/67cd0604fdb2ea52391dd8c9c9ef71206d8bc841) than can be called in OnResume to set a new session id when users returns to the app.

```csharp
protected override void OnResume()
{
    base.OnResume();

    var insights = serviceProvider.GetRequiredService<IInsights>();
    insights.CreateNewSession();
}
```
