### ISSUE TITLE
Custom exception crashes are not being collected

### ISSUE THREAD

**Issue by sang-hyeon** [dhindrik/TinyInsights.Maui#35]
I created and threw a custom exception as shown below, but this exception is not being collected in Application Insights.

```cs
class BaseException  : Exception
{}

class RealException : BaseException
{}
```

I think it might be that the Exception is not being instantiated when `GetException` is called.

https://github.com/dhindrik/TinyInsights.Maui/blob/ce27dbed91d76c0185bfda58576f93d34e70c6d9/TinyInsights/ApplicationInsightsProvider.cs#L265-L272

**Comment by dhindrik** [comment]
Fixed in this commit, https://github.com/dhindrik/TinyInsights.Maui/commit/12efbfb18df6485f69939abbe1f39ec9b2864f97

**Comment by dhindrik** [comment]
@sang-hyeon Thank you for reporting this problem.
