### ISSUE TITLE
iOS app is not sending any log information to Application Insights.

### ISSUE THREAD

**Issue by shushil** [dhindrik/TinyInsights.Maui#36]
Hello first of all thank you for this nugget package.

My App configuration:

TinyInsights.Maui nugget version 1.0.6
.net 8
iOS minimum build target 16.0
Android Min target 10

I have one instance of Application Insight setup for both iOS and Android.
I receive all the logs from Android Application including crash logs and so on. However I don't receive any logs and crash log information via iOS in Application Insights.

I have followed the setup as per document. (as below)
TinnyInsights configuration:
                .UseTinyInsights(builder.Configuration["ApplicationInsights:ConnectionString"], provider =>
                {
                    provider.IsTrackEventsEnabled = true;
                    provider.IsTrackPageViewsEnabled = true;
                    provider.IsTrackErrorsEnabled = true;
                    provider.IsTrackCrashesEnabled = true;
                    provider.IsTrackDependencyEnabled = false;
                    provider.IsAutoTrackPageViewsEnabled = false;
                })

// ILogger setup as:
            builder.Services.AddSingleton<ILogger>((serviceProvider) =>
            {
                var insights = serviceProvider.GetRequiredService<IInsights>();
                var providers = insights.GetProviders();

                if (providers.Any())
                {
                    return (ILogger)providers.First();
                }

                throw new InvalidOperationException("No insights provider found");
            });

            return builder;

Am I missing something?
Do I need to use different instances of Application Insights for each platfom?

**Comment by shushil** [comment]
Yes connection string is correct. Again if connection string is wrong it should not work for Android app right? since i am using same connection for both.

**Comment by dhindrik** [comment]
Sorry, I missunderstood. I thought you had different instances of Application Insights.

I will investigate and see if I can find anything.

**Comment by dhindrik** [comment]
I see the problem in one of my apps too. But not when I run the test app in debug and not in my other published app,

**Comment by dhindrik** [comment]
I was wrong, I did not see the problem in on of my apps. It was just that I was running a branch without the code :P

**Comment by shushil** [comment]
Np thanks for the verification.

**Comment by smardine** [comment]
Hey there, do you figure why you send no log?

Thanks for your time

**Comment by shushil** [comment]
@smardine Not yet, We got busy on different task hopefully get back to it after couple of week.

**Comment by dhindrik** [comment]
@smardine it is not working for you either?

**Comment by smardine** [comment]
It IS working for me, i will send you details of how i implement it

Le mer. 4 déc. 2024, 07:05, Daniel Hindrikes ***@***.***> a
écrit :

**Comment by smardine** [comment]
It is working for me, this is how i implement it

in MauiProgram.cs :

```
.UseTinyInsights("AppInsightKey", (provider) =>
            {
                provider.IsTrackDependencyEnabled = false;
                provider.IsTrackEventsEnabled = true;
                provider.IsTrackErrorsEnabled = false;
                provider.IsTrackPageViewsEnabled = false;
                provider.IsTrackCrashesEnabled = false;
                provider.IsAutoTrackPageViewsEnabled = false;
            })
```

After I send data using a service :
```
public class AppInsightService : IAppInsightService
{
    private readonly IInsights _appInsights;

    public AppInsightService(IInsights appInsights) => _appInsights = appInsights;


    /// <inheritdoc/>
    public void CreateNewSession() => _appInsights?.CreateNewSession();

    public void SetUserId(string userId) => _appInsights?.OverrideAnonymousUserId(userId);

    /// <inheritdoc/>
    public Task TrackStartSessionAsync(Dictionary<string, string> parameters)
    {
        var customDimensions = new Dictionary<string, string>
                            {
                                { "MessageType", "EventLog" },
                                { "Properties", JsonSerializer.Serialize(parameters) }
                            };
        return _appInsights?.TrackEventAsync("StartSession", customDimensions);
    }

    /// <inheritdoc/>
    public Task TrackNavigationAsync(Dictionary<string, string> parameters)
    {
        var customDimensions = new Dictionary<string, string>
                            {
                                { "MessageType", "EventLog" },
                                { "Properties", JsonSerializer.Serialize(parameters) }
                            };
        return _appInsights?.TrackEventAsync("Navigation", customDimensions);
    }
}
```

then, I always call in this order : 

```
  _appInsightService.CreateNewSession();
  // Set AppInsight UserId
  _appInsightService.SetUserId(sessionContext.User.Email);
  _appInsightService.TrackStartSessionAsync(new Dictionary<string, string>
        {
            { "tenantId", sessionContext.User.TenantId },
            { "userId", sessionContext.User.Id.ToString() },
            { "userName", sessionContext.User.Name },
        });
```

Hope this help

**Comment by IeuanWalker** [comment]
also not seen an issue on iOS

**Comment by shushil** [comment]
Finally the iOS app is also logging on the application insight. the issue was related to the MaUi Toolkit version we updated the maui toolkit version to the lastest on also updated tinyInsights nugget to latest and it all started working. So we think the older version of MaUi toolkit was producing regular .net version of dll rather then ios version of dll.
