### ISSUE TITLE
Monitor App usage time

### ISSUE THREAD

**Issue by FrankPohl** [dhindrik/TinyInsights.Maui#40]
Hi Daniel,
from my point of view the duration of the app usage is a very useful metric.
What is your recommendation to measure that in the code?

So I don't know whether this tis is a question or a feature request.

Kind regards
Frank

**Comment by dhindrik** [comment]
Right now you can query the first and last page view in a session. But it will not give you any exact value. But I plan to add duration to page views and after that is done you will be able to get more exact session times.
