### ISSUE TITLE
Ilogger

### ISSUE THREAD

**Issue by Kebechet** [dhindrik/TinyInsights.Maui#6]
Hello, interesting package.
Did you consider Ilogger integration ?

**Comment by dhindrik** [comment]
I did not, but it is a great idea. I will start to look into it.

**Comment by dhindrik** [comment]
What do you think about this implementation? https://github.com/dhindrik/TinyInsights.Maui/pull/7

**Comment by Kebechet** [comment]
@dhindrik I gave you some comments/questions to the PR
